notion

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -45,12 +45,13 @@ jobs:
           ls -a1 ./
           cd ./loconotion
           pip install -r ./requirements.txt
-          rm -rfv ./dist && mkdir -p ./dist
+          rm -rfv ./dist "${{ env.DISTRO }}"
+          mkdir -p ./dist "${{ env.DISTRO }}"
           cp -fv ../_site/config.toml ./site.toml
           python loconotion "./site.toml" --chromedriver /usr/bin/chromedriver
-          echo "${{env.SOURCE_BRANCH}}" > "${{env.DISTRO}}/source.txt"
-          cp -fv ../_site/LICENSE.md > "${{env.DISTRO}}/LICENSE.md"
-          ls -a1 "${{env.DISTRO}}"
+          echo "${{env.SOURCE_BRANCH}}" > "${{ env.DISTRO }}/source.txt"
+          cp -fv ../_site/LICENSE.md > "${{ env.DISTRO }}/LICENSE.md"
+          ls -a1 "${{ env.DISTRO }}"
       - name: Publish HTML to IPFS
         run: |
           set -x
@@ -58,17 +59,17 @@ jobs:
           set -e
           ipfs-api delete $IPFS_UPLOAD_NAME --key=${{secrets.PINATA_API_JWT}} --verbose=true || echo "WARNING: Failed to delete file with name '$IPFS_UPLOAD_NAME' request failed or it might not exist"
           set +e
-          ipfs-api pin "${{env.DISTRO}}" $IPFS_UPLOAD_NAME --key=${{secrets.PINATA_API_JWT}} --verbose=true | tee -a ./ipfs-pin.log || echo "ERROR: Failed to pin web app"
+          ipfs-api pin "${{ env.DISTRO }}" $IPFS_UPLOAD_NAME --key=${{secrets.PINATA_API_JWT}} --verbose=true | tee -a ./ipfs-pin.log || echo "ERROR: Failed to pin web app"
           IPFS_HASH=$(cat ./ipfs-pin.log | tail -n 1 | bash-utils jsonParse ".hash" || echo "")
           [ -z "$IPFS_HASH" ] && echo "ERROR: IPFS Upload Failed" && exit 1
-          echo "$IPFS_HASH" > "${{env.DISTRO}}/ipfs-cid.txt"
+          echo "$IPFS_HASH" > "${{ env.DISTRO }}/ipfs-cid.txt"
           echo "IPFS_HASH=$IPFS_HASH" >> $GITHUB_ENV
       - name: Release
         uses: s0/git-publish-subdir-action@develop
         env:
             REPO: self
             BRANCH: "${{ env.SOURCE_BRANCH }}-release"
-            FOLDER: "${{env.DISTRO}}"
+            FOLDER: "${{ env.DISTRO }}"
             GITHUB_TOKEN: ${{ secrets.REPO_ACCESS }}
       - name: Create PR from dev to master branch
         # ref. repo-sync/pull-request is broken, using cea2aj/pull-request instead
