sanitize release files

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,10 +21,12 @@ jobs:
           mkdir -p /github/home/.cache/pip
           git config --global --add safe.directory /github/home/.cache/pip
           git config --global --add safe.directory $PWD
+          echo "INDEX_MODE=redirect" >> $GITHUB_ENV
           echo "SUBDOMAIN=docs" >> $GITHUB_ENV
           echo "DNS=kira.network" >> $GITHUB_ENV
           echo "SOURCE_BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
           echo "DISTRO=${GITHUB_WORKSPACE}/loconotion/dist/notion" >> $GITHUB_ENV
+          echo "RELEASE=${GITHUB_WORKSPACE}/release" >> $GITHUB_ENV
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
@@ -43,21 +45,19 @@ jobs:
           path: _site
       - name: Install Loconotion & Build
         run: |
-          ls -a1 ./
           cd ./loconotion
           pip install -r ./requirements.txt
-          rm -rfv ./dist "${{ env.DISTRO }}"
-          mkdir -p ./dist "${{ env.DISTRO }}"
+          rm -rfv ./dist "${{env.DISTRO}}" "${{env.RELEASE}}"
+          mkdir -p ./dist "${{env.DISTRO}}" "${{env.RELEASE}}"
           cp -fv ../_site/config.toml ./site.toml
           python loconotion "./site.toml" --chromedriver /usr/bin/chromedriver
-          echo "${{env.SOURCE_BRANCH}}" > "${{ env.DISTRO }}/source.txt"
-          echo "${{env.SUBDOMAIN}}.${{env.DNS}}" > "${{ env.DISTRO }}/CNAME"
-          mkdir -p "${{ env.DISTRO }}/embed" "${{ env.DISTRO }}/redirect"
+          echo "${{env.SOURCE_BRANCH}}" > "${{env.RELEASE}}/source.txt"
+          echo "${{env.SUBDOMAIN}}.${{env.DNS}}" > "${{env.RELEASE}}/CNAME"
+          cp -fv ../_site/LICENSE.md "${{env.RELEASE}}/LICENSE.md"
+          cp -fv ../_site/${INDEX_MODE}.html "${{env.RELEASE}}/index.html"
           ls -a1 ../_site
-          cp -fv ../_site/LICENSE.md "${{ env.DISTRO }}/LICENSE.md"
-          cp -fv ../_site/embed.html "${{ env.DISTRO }}/embed/index.html"
-          cp -fv ../_site/redirect.html "${{ env.DISTRO }}/redirect/index.html"
-          ls -a1 "${{ env.DISTRO }}"
+          ls -a1 "${{env.DISTRO}}"
+          ls -a1 "${{env.RELEASE}}"
       - name: Publish HTML to IPFS
         run: |
           set -x
@@ -65,26 +65,35 @@ jobs:
           set -e
           ipfs-api delete $IPFS_UPLOAD_NAME --key=${{secrets.PINATA_API_JWT}} --verbose=true || echo "WARNING: Failed to delete file with name '$IPFS_UPLOAD_NAME' request failed or it might not exist"
           set +e
-          ipfs-api pin "${{ env.DISTRO }}" $IPFS_UPLOAD_NAME --key=${{secrets.PINATA_API_JWT}} --verbose=true | tee -a ./ipfs-pin.log || echo "ERROR: Failed to pin web app"
+          ipfs-api pin "${{env.DISTRO}}" $IPFS_UPLOAD_NAME --key=${{secrets.PINATA_API_JWT}} --verbose=true | tee -a ./ipfs-pin.log || echo "ERROR: Failed to pin web app"
           IPFS_HASH=$(cat ./ipfs-pin.log | tail -n 1 | bash-utils jsonParse ".hash" || echo "")
           [ -z "$IPFS_HASH" ] && echo "ERROR: IPFS Upload Failed" && exit 1
-          echo "$IPFS_HASH" > "${{ env.DISTRO }}/ipfs-cid.txt"
           echo "IPFS_HASH=$IPFS_HASH" >> $GITHUB_ENV
+      - name: Save changes to release folder
+        run: |
+          ZIP_FILENAME="${{env.SUBDOMAIN}}.${{env.DNS}}.zip"
+          cd ${{env.DISTRO}}"
+          rm -fv $ZIP_FILENAME
+          zip -r $ZIP_FILENAME *
+          cp -fv ${{env.DISTRO}}/$ZIP_FILENAME "${{env.RELEASE}}/$ZIP_FILENAME"
+
+          echo "${{env.IPFS_HASH}}" > "${{env.DISTRO}}/ipfs-cid.txt"
+
           TARGET_VAR="IPFS_CID"
-          REPLACE_VAR="https://ipfs.${{env.DNS}}/ipfs/$IPFS_HASH"
+          REPLACE_VAR="https://ipfs.${{env.DNS}}/ipfs/${{env.IPFS_HASH}}"
           ESCAPED_VAR=$(echo "$REPLACE_VAR" | sed 's/\//\\\//g; s/&/\\&/g; s/\?/\\?/g')
-          sed -i "s/$TARGET_VAR/$ESCAPED_VAR/g" "${{ env.DISTRO }}/embed/index.html"
-          sed -i "s/$TARGET_VAR/$ESCAPED_VAR/g" "${{ env.DISTRO }}/redirect/index.html"
+          sed -i "s/$TARGET_VAR/$ESCAPED_VAR/g" "${{env.RELEASE}}/index.html"
+          
           TARGET_VAR="GITHUB_REPO"
           REPLACE_VAR="https://github.com/KiraCore/${{env.SUBDOMAIN}}.${{env.DNS}}/tree/${{env.SOURCE_BRANCH}}-release"
           ESCAPED_VAR=$(echo "$REPLACE_VAR" | sed 's/\//\\\//g; s/&/\\&/g; s/\?/\\?/g')
-          sed -i "s/$TARGET_VAR/$ESCAPED_VAR/g" "${{ env.DISTRO }}/redirect/index.html"
-      - name: Release
+          sed -i "s/$TARGET_VAR/$ESCAPED_VAR/g" "${{env.RELEASE}}/index.html"
+      - name: Publish release folder
         uses: s0/git-publish-subdir-action@develop
         env:
             REPO: self
             BRANCH: "${{ env.SOURCE_BRANCH }}-release"
-            FOLDER: "${{ env.DISTRO }}"
+            FOLDER: "${{ env.RELEASE }}"
             GITHUB_TOKEN: ${{ secrets.REPO_ACCESS }}
       - name: Cleanup
         run: |
